-- =============================================================================
-- 테스트 픽스처: 원격(xlsfnfolrrhxsxazmhjb)에 있던 레거시 예약 앱 public 객체 모양 (2026-09-28 읽기 전용 캡처)
-- 로컬/스테이징 전용. legacy_booking_cleanup.sql 과 원격 모사 replica 검증에서 \ir 로 사용한다.
-- 테이블·제약·인덱스·함수·트리거·RLS 정책·권한·realtime publication 등록을 원격과 동일하게 재현한다.
-- =============================================================================
-- 로컬 replay 스텁(반환형이 다름)이 있으면 먼저 제거해 원격과 같은 정의로 다시 만든다
DROP FUNCTION IF EXISTS public.get_booking_slots(uuid, date, bigint);
DROP FUNCTION IF EXISTS public.is_booking_customer(bigint, uuid);
DROP FUNCTION IF EXISTS public.is_booking_owner(bigint, uuid);
DROP FUNCTION IF EXISTS public.create_booking_change_request(bigint, date, time without time zone, time without time zone, bigint, text);
DROP FUNCTION IF EXISTS public.respond_booking_change_request(bigint, text, text);

-- ===== tables (FK order) =====
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  slug text NOT NULL,
  business_name text NOT NULL,
  start_hour time without time zone DEFAULT '09:00:00'::time without time zone NOT NULL,
  end_hour time without time zone DEFAULT '18:00:00'::time without time zone NOT NULL,
  slot_interval integer DEFAULT 30 NOT NULL,
  description text,
  category text,
  logo_url text,
  cover_url text
);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_slug_key UNIQUE (slug);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE INDEX idx_profiles_category ON public.profiles USING btree (category) WHERE (category IS NOT NULL);
CREATE INDEX idx_profiles_business_name ON public.profiles USING btree (business_name);
CREATE INDEX idx_profiles_slug ON public.profiles USING btree (slug);

CREATE TABLE public.customer_profiles (
  id uuid NOT NULL,
  display_name text NOT NULL,
  phone text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.customer_profiles ADD CONSTRAINT customer_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.customer_profiles ADD CONSTRAINT customer_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE INDEX idx_customer_profiles_phone ON public.customer_profiles USING btree (phone);

CREATE TABLE public.services (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  shop_id uuid NOT NULL,
  name text NOT NULL,
  duration integer NOT NULL,
  price numeric DEFAULT 0 NOT NULL
);
ALTER TABLE public.services ADD CONSTRAINT services_pkey PRIMARY KEY (id);
ALTER TABLE public.services ADD CONSTRAINT services_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
CREATE INDEX idx_services_shop_id ON public.services USING btree (shop_id);

CREATE TABLE public.blocked_times (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  shop_id uuid NOT NULL,
  date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  reason text
);
ALTER TABLE public.blocked_times ADD CONSTRAINT blocked_times_pkey PRIMARY KEY (id);
ALTER TABLE public.blocked_times ADD CONSTRAINT blocked_times_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
CREATE INDEX idx_blocked_times_shop_date ON public.blocked_times USING btree (shop_id, date);

CREATE TABLE public.bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  shop_id uuid NOT NULL,
  service_id bigint,
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  booking_date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  status text DEFAULT 'confirmed'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  customer_user_id uuid
);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.bookings ADD CONSTRAINT bookings_customer_user_id_fkey FOREIGN KEY (customer_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
CREATE INDEX idx_bookings_shop_date ON public.bookings USING btree (shop_id, booking_date);
CREATE INDEX idx_bookings_customer_user_id ON public.bookings USING btree (customer_user_id);
CREATE INDEX idx_bookings_customer_phone ON public.bookings USING btree (customer_phone);

CREATE TABLE public.booking_change_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  booking_id bigint NOT NULL,
  shop_id uuid NOT NULL,
  requested_by text NOT NULL,
  requester_user_id uuid NOT NULL,
  new_booking_date date NOT NULL,
  new_start_time time without time zone NOT NULL,
  new_end_time time without time zone NOT NULL,
  new_service_id bigint,
  reason text NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  response_note text,
  responded_at timestamp with time zone,
  responded_by_user_id uuid,
  created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.booking_change_requests ADD CONSTRAINT booking_change_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.booking_change_requests ADD CONSTRAINT booking_change_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text])));
ALTER TABLE public.booking_change_requests ADD CONSTRAINT booking_change_requests_requested_by_check CHECK ((requested_by = ANY (ARRAY['owner'::text, 'customer'::text])));
ALTER TABLE public.booking_change_requests ADD CONSTRAINT booking_change_requests_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.booking_change_requests ADD CONSTRAINT booking_change_requests_responded_by_user_id_fkey FOREIGN KEY (responded_by_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.booking_change_requests ADD CONSTRAINT booking_change_requests_new_service_id_fkey FOREIGN KEY (new_service_id) REFERENCES public.services(id);
ALTER TABLE public.booking_change_requests ADD CONSTRAINT booking_change_requests_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;
ALTER TABLE public.booking_change_requests ADD CONSTRAINT booking_change_requests_requester_user_id_fkey FOREIGN KEY (requester_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE INDEX idx_bcr_booking_id ON public.booking_change_requests USING btree (booking_id);
CREATE UNIQUE INDEX idx_bcr_one_pending_per_booking ON public.booking_change_requests USING btree (booking_id) WHERE (status = 'pending'::text);
CREATE INDEX idx_bcr_shop_id_status ON public.booking_change_requests USING btree (shop_id, status);

-- ===== functions =====
CREATE OR REPLACE FUNCTION public.check_booking_overlap()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.status <> 'confirmed' THEN
    RETURN NEW;
  END IF;

  IF EXISTS (
    SELECT 1 FROM bookings
    WHERE shop_id = NEW.shop_id
      AND booking_date = NEW.booking_date
      AND status = 'confirmed'
      AND id IS DISTINCT FROM NEW.id
      AND NOT (NEW.end_time <= start_time OR NEW.start_time >= end_time)
  ) THEN
    RAISE EXCEPTION '해당 시간대에 이미 예약이 존재합니다.';
  END IF;

  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.prevent_direct_booking_schedule_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF (OLD.booking_date, OLD.start_time, OLD.end_time, OLD.service_id)
     IS DISTINCT FROM
     (NEW.booking_date, NEW.start_time, NEW.end_time, NEW.service_id) THEN
    IF current_setting('app.booking_change_apply', true) IS DISTINCT FROM 'true' THEN
      RAISE EXCEPTION 'BOOKING_SCHEDULE_LOCKED';
    END IF;
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_booking_slots(p_shop_id uuid, p_booking_date date, p_exclude_booking_id bigint DEFAULT NULL::bigint)
 RETURNS TABLE(start_time time without time zone, end_time time without time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT b.start_time, b.end_time
  FROM public.bookings b
  WHERE b.shop_id = p_shop_id
    AND b.booking_date = p_booking_date
    AND b.status = 'confirmed'
    AND b.id IS DISTINCT FROM p_exclude_booking_id;
$function$;

CREATE OR REPLACE FUNCTION public.is_booking_customer(p_booking_id bigint, p_user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM bookings b
    WHERE b.id = p_booking_id
      AND b.status = 'confirmed'
      AND NOT EXISTS (SELECT 1 FROM profiles WHERE profiles.id = p_user_id)
      AND (
        b.customer_user_id = p_user_id
        OR (
          b.customer_user_id IS NULL
          AND b.customer_phone = (
            SELECT cp.phone FROM customer_profiles cp WHERE cp.id = p_user_id
          )
        )
      )
  );
$function$;

CREATE OR REPLACE FUNCTION public.is_booking_owner(p_booking_id bigint, p_user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM bookings b
    WHERE b.id = p_booking_id AND b.shop_id = p_user_id
  );
$function$;

CREATE OR REPLACE FUNCTION public.create_booking_change_request(p_booking_id bigint, p_new_booking_date date, p_new_start_time time without time zone, p_new_end_time time without time zone, p_new_service_id bigint, p_reason text)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  b bookings%ROWTYPE;
  v_role text;
  v_request_id bigint;
  v_reason text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'UNAUTHORIZED';
  END IF;

  v_reason := trim(p_reason);
  IF v_reason IS NULL OR length(v_reason) < 2 THEN
    RAISE EXCEPTION 'REASON_REQUIRED';
  END IF;
  IF length(v_reason) > 200 THEN
    RAISE EXCEPTION 'REASON_TOO_LONG';
  END IF;

  SELECT * INTO b FROM bookings WHERE id = p_booking_id FOR UPDATE;
  IF NOT FOUND OR b.status <> 'confirmed' THEN
    RAISE EXCEPTION 'BOOKING_NOT_CHANGEABLE';
  END IF;

  IF EXISTS (
    SELECT 1 FROM booking_change_requests
    WHERE booking_id = p_booking_id AND status = 'pending'
  ) THEN
    RAISE EXCEPTION 'PENDING_REQUEST_EXISTS';
  END IF;

  IF is_booking_owner(p_booking_id, auth.uid()) THEN
    v_role := 'owner';
  ELSIF is_booking_customer(p_booking_id, auth.uid()) THEN
    v_role := 'customer';
  ELSE
    RAISE EXCEPTION 'UNAUTHORIZED';
  END IF;

  IF p_new_service_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM services s
    WHERE s.id = p_new_service_id AND s.shop_id = b.shop_id
  ) THEN
    RAISE EXCEPTION 'INVALID_SERVICE';
  END IF;

  IF p_new_end_time <= p_new_start_time THEN
    RAISE EXCEPTION 'INVALID_TIME_RANGE';
  END IF;

  INSERT INTO booking_change_requests (
    booking_id, shop_id, requested_by, requester_user_id,
    new_booking_date, new_start_time, new_end_time, new_service_id, reason
  ) VALUES (
    p_booking_id, b.shop_id, v_role, auth.uid(),
    p_new_booking_date, p_new_start_time, p_new_end_time, p_new_service_id, v_reason
  )
  RETURNING id INTO v_request_id;

  RETURN v_request_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.respond_booking_change_request(p_request_id bigint, p_action text, p_response_note text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  req booking_change_requests%ROWTYPE;
  b bookings%ROWTYPE;
  v_note text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'UNAUTHORIZED';
  END IF;

  SELECT * INTO req FROM booking_change_requests WHERE id = p_request_id FOR UPDATE;
  IF NOT FOUND OR req.status <> 'pending' THEN
    RAISE EXCEPTION 'REQUEST_NOT_PENDING';
  END IF;

  v_note := NULLIF(trim(p_response_note), '');

  IF p_action = 'cancel' THEN
    IF req.requester_user_id <> auth.uid() THEN
      RAISE EXCEPTION 'UNAUTHORIZED';
    END IF;
    UPDATE booking_change_requests SET
      status = 'cancelled',
      responded_at = NOW(),
      responded_by_user_id = auth.uid(),
      response_note = v_note
    WHERE id = p_request_id;
    RETURN;
  END IF;

  IF p_action = 'approve' THEN
    IF req.requested_by = 'owner' AND NOT is_booking_customer(req.booking_id, auth.uid()) THEN
      RAISE EXCEPTION 'UNAUTHORIZED';
    END IF;
    IF req.requested_by = 'customer' AND NOT is_booking_owner(req.booking_id, auth.uid()) THEN
      RAISE EXCEPTION 'UNAUTHORIZED';
    END IF;

    SELECT * INTO b FROM bookings WHERE id = req.booking_id FOR UPDATE;
    IF b.status <> 'confirmed' THEN
      RAISE EXCEPTION 'BOOKING_NOT_CHANGEABLE';
    END IF;

    PERFORM set_config('app.booking_change_apply', 'true', true);
    UPDATE bookings SET
      booking_date = req.new_booking_date,
      start_time = req.new_start_time,
      end_time = req.new_end_time,
      service_id = COALESCE(req.new_service_id, b.service_id)
    WHERE id = req.booking_id;

    UPDATE booking_change_requests SET
      status = 'approved',
      responded_at = NOW(),
      responded_by_user_id = auth.uid(),
      response_note = v_note
    WHERE id = p_request_id;
    RETURN;
  END IF;

  IF p_action = 'reject' THEN
    IF req.requested_by = 'owner' AND NOT is_booking_customer(req.booking_id, auth.uid()) THEN
      RAISE EXCEPTION 'UNAUTHORIZED';
    END IF;
    IF req.requested_by = 'customer' AND NOT is_booking_owner(req.booking_id, auth.uid()) THEN
      RAISE EXCEPTION 'UNAUTHORIZED';
    END IF;

    UPDATE booking_change_requests SET
      status = 'rejected',
      responded_at = NOW(),
      responded_by_user_id = auth.uid(),
      response_note = v_note
    WHERE id = p_request_id;
    RETURN;
  END IF;

  RAISE EXCEPTION 'INVALID_ACTION';
END;
$function$;

-- function ACLs at capture
REVOKE ALL ON FUNCTION public.get_booking_slots(uuid, date, bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_booking_slots(uuid, date, bigint) TO postgres, service_role;
REVOKE ALL ON FUNCTION public.is_booking_customer(bigint, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_booking_customer(bigint, uuid) TO postgres, service_role;
REVOKE ALL ON FUNCTION public.is_booking_owner(bigint, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_booking_owner(bigint, uuid) TO postgres, service_role;
REVOKE ALL ON FUNCTION public.create_booking_change_request(bigint, date, time without time zone, time without time zone, bigint, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_booking_change_request(bigint, date, time without time zone, time without time zone, bigint, text) TO postgres, service_role;
REVOKE ALL ON FUNCTION public.respond_booking_change_request(bigint, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.respond_booking_change_request(bigint, text, text) TO postgres, service_role;
GRANT EXECUTE ON FUNCTION public.check_booking_overlap() TO PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.prevent_direct_booking_schedule_change() TO PUBLIC, anon, authenticated, service_role;

-- ===== triggers =====
CREATE TRIGGER trg_prevent_direct_booking_schedule_change BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.prevent_direct_booking_schedule_change();
CREATE TRIGGER trg_check_booking_overlap BEFORE INSERT OR UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.check_booking_overlap();

-- ===== RLS + policies =====
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocked_times ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_change_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read profiles" ON public.profiles AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Owners manage own profile" ON public.profiles AS PERMISSIVE FOR ALL TO authenticated USING ((id = auth.uid())) WITH CHECK ((id = auth.uid()));
CREATE POLICY "Customers manage own profile" ON public.customer_profiles AS PERMISSIVE FOR ALL TO authenticated USING ((id = auth.uid())) WITH CHECK ((id = auth.uid()));
CREATE POLICY "Owners manage own services" ON public.services AS PERMISSIVE FOR ALL TO authenticated USING ((shop_id = auth.uid())) WITH CHECK ((shop_id = auth.uid()));
CREATE POLICY "Public read services" ON public.services AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Owners manage own blocked_times" ON public.blocked_times AS PERMISSIVE FOR ALL TO authenticated USING ((shop_id = auth.uid())) WITH CHECK ((shop_id = auth.uid()));
CREATE POLICY "Public read blocked_times" ON public.blocked_times AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Customers read own bookings" ON public.bookings AS PERMISSIVE FOR SELECT TO authenticated USING (((NOT (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE (profiles.id = auth.uid())))) AND ((customer_user_id = auth.uid()) OR ((customer_user_id IS NULL) AND (customer_phone = ( SELECT cp.phone
   FROM public.customer_profiles cp
  WHERE (cp.id = auth.uid())))))));
CREATE POLICY "Anon insert bookings" ON public.bookings AS PERMISSIVE FOR INSERT TO anon WITH CHECK (((shop_id IN ( SELECT profiles.id
   FROM public.profiles)) AND (service_id IN ( SELECT services.id
   FROM public.services
  WHERE (services.shop_id = bookings.shop_id)))));
CREATE POLICY "Customer insert bookings" ON public.bookings AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((EXISTS ( SELECT 1
   FROM public.customer_profiles
  WHERE (customer_profiles.id = auth.uid()))) AND (NOT (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE (profiles.id = auth.uid())))) AND (shop_id IN ( SELECT profiles.id
   FROM public.profiles)) AND (service_id IN ( SELECT services.id
   FROM public.services
  WHERE (services.shop_id = bookings.shop_id))) AND ((customer_user_id IS NULL) OR (customer_user_id = auth.uid()))));
CREATE POLICY "Owners manage own bookings" ON public.bookings AS PERMISSIVE FOR ALL TO authenticated USING ((shop_id = auth.uid())) WITH CHECK ((shop_id = auth.uid()));
CREATE POLICY "Customers read own change requests" ON public.booking_change_requests AS PERMISSIVE FOR SELECT TO authenticated USING (((NOT (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE (profiles.id = auth.uid())))) AND (EXISTS ( SELECT 1
   FROM public.bookings b
  WHERE ((b.id = booking_change_requests.booking_id) AND ((b.customer_user_id = auth.uid()) OR ((b.customer_user_id IS NULL) AND (b.customer_phone = ( SELECT cp.phone
           FROM public.customer_profiles cp
          WHERE (cp.id = auth.uid()))))))))));
CREATE POLICY "Owners read shop change requests" ON public.booking_change_requests AS PERMISSIVE FOR SELECT TO authenticated USING ((shop_id = auth.uid()));

-- ===== table / sequence grants at capture (relacl) =====
-- profiles, customer_profiles, services, blocked_times, booking_change_requests:
--   {postgres=arwdDxtm, anon=arwdDxtm, authenticated=arwdDxtm, service_role=arwdDxtm}
-- bookings: anon=awdDxtm (no SELECT), others arwdDxtm
GRANT ALL ON public.profiles, public.customer_profiles, public.services, public.blocked_times, public.booking_change_requests, public.bookings TO postgres, anon, authenticated, service_role;
REVOKE SELECT ON public.bookings FROM anon;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.services_id_seq, public.blocked_times_id_seq, public.bookings_id_seq, public.booking_change_requests_id_seq TO postgres, anon, authenticated, service_role;

-- ===== realtime publication membership at capture =====
DO $pub$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END $pub$;
ALTER PUBLICATION supabase_realtime ADD TABLE public.bookings, public.profiles, public.services;
