import { POS_PAYMENT_METHODS, SALE_PAYMENT_METHOD_LABELS } from '../../types/sale';

/** 판매 내역 UI 문구 */
export const SALE_HISTORY_COPY = {
  title: '판매 내역',
  description: '날짜별 판매 기록을 확인합니다',
  searchPlaceholder: '판매번호·고객·상품 검색',
  noOrg: '사업장을 선택해 주세요',
  loadError: '판매 내역을 불러오지 못했습니다',
  emptyTitle: '판매 내역이 없습니다',
  emptyDescription: '해당 날짜에 완료된 판매가 없습니다',
  emptyFilterTitle: '조건에 맞는 판매가 없습니다',
  emptyFilterDescription: '날짜·필터·검색어를 바꿔 보세요',
  dateLabel: '날짜',
  paymentAll: '전체',
  customerAll: '전체 고객',
  customerMember: '회원',
  customerGuest: '비회원',
  guestName: '비회원',
  saleNo: '판매번호',
  saleTime: '판매시간',
  customer: '고객',
  products: '상품',
  total: '총액',
  payment: '결제수단',
  itemCount: (n: number) => `${n}개 상품`,
  moreProducts: (n: number) => `외 ${n}건`,
  detailTitle: '판매 상세',
  detailItems: '상품 목록',
  qty: '수량',
  unitPrice: '판매가',
  discount: '할인',
  lineAmount: '금액',
  close: '닫기',
  qtyUnit: '개',
  returnAction: '반품',
  returnTitle: '반품 처리',
  returnHint: '반품할 상품과 수량을 선택한 뒤 환불을 확정합니다',
  returnSold: '판매',
  returnDone: '반품됨',
  returnRemain: '반품 가능',
  returnQty: '반품 수량',
  returnReason: '반품 사유 (선택)',
  returnReasonPlaceholder: '예: 고객 요청, 불량 등',
  returnTotal: '환불 예정 금액',
  returnConfirm: '환불 처리 확정',
  returnConfirming: '처리 중…',
  returnCancel: '취소',
  returnNeedItem: '반품할 상품 수량을 입력해 주세요.',
  returnExceed: '반품 가능 수량을 초과할 수 없습니다.',
  returnSuccess: (amount: string) => `반품이 완료되었습니다. ${amount}`,
  returnError: '반품 처리에 실패했습니다.',
  returnNoneLeft: '반품 가능한 수량이 없습니다.',
  returnHistory: '반품 이력',
  returnedQtyLabel: '반품',
} as const;

export const HISTORY_PAYMENT_TABS = [
  { id: 'ALL' as const, label: SALE_HISTORY_COPY.paymentAll },
  ...POS_PAYMENT_METHODS.map((id) => ({
    id,
    label: SALE_PAYMENT_METHOD_LABELS[id],
  })),
];
