import {
  POS_PAYMENT_METHODS,
  SALE_PAYMENT_METHOD_LABELS,
} from '../../types/sale';

/** 판매(POS) 화면 문구 */
export const SALE_POS_COPY = {
  title: '판매',
  description: '상품을 담고 결제수단을 선택한 뒤 판매를 완료합니다',
  searchPlaceholder: '상품명 검색',
  emptyCatalog: '판매 가능한 상품이 없습니다',
  emptyCatalogHint: '상품 메뉴에서 판매중 상품을 등록해 주세요',
  emptySearch: '검색 결과가 없습니다',
  noOrg: '사업장을 선택해 주세요',
  loadError: '상품을 불러오지 못했습니다',
  singleOption: '단일 상품',
  qtyUnit: '개',
  cartTitle: '장바구니',
  cartEmpty: '담긴 상품이 없습니다',
  cartCount: (n: number) => `${n}건`,
  totalLabel: '총액',
  checkout: '결제하기',
  remove: '삭제',
  increaseQty: '수량 증가',
  decreaseQty: '수량 감소',
  checkoutTitle: '판매 완료',
  customerOptional: '고객 (선택)',
  customerNone: '고객 없이 판매할 수 있습니다',
  customerSearchPlaceholder: '고객명·전화 검색',
  customerClear: '선택 해제',
  customerNoPhone: '전화 없음',
  customerSearching: '검색 중…',
  customerNoResults: '검색 결과가 없습니다',
  customerSearchError: '고객 검색에 실패했습니다.',
  customerRegister: '신규 등록',
  customerRegisterCancel: '검색으로',
  customerName: '고객명',
  customerNamePlaceholder: '이름',
  customerPhone: '전화번호',
  customerPhonePlaceholder: '선택 입력',
  customerRegisterSubmit: '등록 후 선택',
  customerRegistering: '등록 중…',
  customerNeedName: '고객 이름을 입력해 주세요.',
  customerRegisterError: '고객 등록에 실패했습니다.',
  paymentMethod: '결제수단',
  itemsLabel: '판매 상품',
  lineAmount: '금액',
  qtyLabel: '수량',
  optionLabel: '옵션',
  productLabel: '상품명',
  confirmSale: '판매 완료',
  confirming: '처리 중…',
  cancel: '취소',
  needItems: '장바구니에 상품을 담아 주세요.',
  needPayment: '결제수단을 선택해 주세요.',
  saleError: '판매 저장에 실패했습니다.',
  saleDone: (total: string) => `판매가 완료되었습니다. ${total}`,
  stockShortTitle: '재고 부족',
  stockShortConfirm: '그래도 판매',
  stockShortMessage: (lines: string) =>
    `아래 상품의 재고가 부족합니다.\n그래도 판매를 완료할까요?\n\n${lines}`,
  stockShortLine: (label: string, available: number, required: number) =>
    `· ${label}: 현재 ${available}개 / 판매 ${required}개`,
  pointsSection: '포인트 사용',
  pointsBalance: '현재 포인트',
  pointsUse: '사용할 포인트',
  pointsUsePlaceholder: '0',
  pointsPayable: '최종 결제금액',
  pointsUnit: 'P',
  pointsHint: '1P = 1원. 결제금액을 초과해 사용할 수 없습니다.',
  pointsDisabled: '포인트 사용이 꺼져 있거나 잔액이 없습니다.',
  pointsNeedCustomer: '포인트를 사용하려면 고객을 선택해 주세요.',
  pointsExceed: '사용 포인트는 결제금액·잔액을 초과할 수 없습니다.',
} as const;

export const POS_PAYMENT_OPTIONS = POS_PAYMENT_METHODS.map((id) => ({
  id,
  label: SALE_PAYMENT_METHOD_LABELS[id],
}));
