/** 재고 조회 UI 문구 */
export const INVENTORY_LIST_COPY = {
  title: '재고',
  description: '상품·옵션별 현재 재고를 확인합니다',
  /** Staff — 입고·조정 없이 조회만 */
  descriptionReadOnly: '상품·옵션별 현재 재고를 조회합니다 (변경은 관리자만 가능)',
  searchPlaceholder: '상품명 검색',
  filterAll: '전체',
  filterLow: '재고 부족',
  filterOut: '재고 없음',
  emptyTitle: '표시할 재고가 없습니다',
  emptyDescription: '상품을 등록하면 재고 현황이 여기에 표시됩니다',
  emptyFilterTitle: '조건에 맞는 재고가 없습니다',
  emptyFilterDescription: '검색어나 필터를 바꿔 보세요',
  noOrg: '사업장을 선택해 주세요',
  loadError: '재고를 불러오지 못했습니다',
  colProduct: '상품명',
  colOption: '옵션',
  colQty: '현재 수량',
  colStatus: '판매 상태',
  singleOption: '단일 상품',
  statusActive: '판매중',
  statusInactive: '판매중지',
  qtyUnit: '개',
  inbound: '입고',
  inboundTitle: '상품 입고',
  inboundHint: '입고 수량은 현재 재고에 더해지며, 이동 이력에 기록됩니다.',
  inboundProduct: '상품',
  inboundVariant: '옵션',
  inboundSelectProduct: '상품 선택',
  inboundSelectVariant: '옵션 선택',
  inboundQty: '입고 수량',
  inboundMemo: '메모',
  inboundMemoPlaceholder: '입고 사유 등 (선택)',
  inboundCurrentQty: '현재 재고',
  inboundSubmit: '입고 완료',
  inboundSaving: '처리 중…',
  inboundNeedProduct: '상품을 선택해 주세요.',
  inboundNeedVariant: '옵션을 선택해 주세요.',
  inboundNeedQty: '입고 수량을 입력해 주세요.',
  inboundError: '입고 처리에 실패했습니다.',
  inboundDone: (after: number) => `입고가 완료되었습니다. 현재 재고 ${after}개`,
  adjust: '조정',
  adjustTitle: '재고 조정',
  adjustHint:
    '현재 수량과 실제 수량의 차이를 입력합니다. 조정 이력(adjustment)이 반드시 남습니다.',
  adjustProduct: '상품',
  adjustVariant: '옵션',
  adjustSelectProduct: '상품 선택',
  adjustSelectVariant: '옵션 선택',
  adjustCurrentQty: '현재 수량',
  adjustQty: '조정 수량',
  adjustQtyPlaceholder: '예: -2 (감소) 또는 2 (증가)',
  adjustQtyHint: '실제 − 현재 = 조정. 예: 현재 20 → 실제 18이면 −2',
  adjustAfterQty: '조정 후 수량',
  adjustReason: '사유',
  adjustReasonSelect: '사유 선택',
  adjustReasonOther: '기타 사유',
  adjustReasonOtherPlaceholder: '조정 사유를 입력해 주세요',
  adjustSubmit: '조정 저장',
  adjustSaving: '처리 중…',
  adjustNeedProduct: '상품을 선택해 주세요.',
  adjustNeedVariant: '옵션을 선택해 주세요.',
  adjustNeedQty: '조정 수량을 입력해 주세요. (0 제외)',
  adjustNeedReason: '조정 사유를 선택해 주세요.',
  adjustNeedReasonDetail: '기타 사유를 입력해 주세요.',
  adjustError: '재고 조정에 실패했습니다.',
  adjustDone: (delta: number, after: number) =>
    `조정이 완료되었습니다. (${delta > 0 ? '+' : ''}${delta}) 현재 재고 ${after}개`,
  cancel: '취소',
} as const;
