/**
 * Navigation tab contract.
 * UI Context(AppContext)와 분리한다. React / App state를 두지 않는다.
 */
export type NavTab =
  | 'dashboard'
  | 'students'
  | 'parents'
  | 'enrollment-requests'
  | 'classes'
  | 'timetable'
  | 'attendance'
  | 'check-in'
  | 'tuition'
  | 'unpaid'
  | 'textbooks'
  | 'finance'
  | 'income'
  | 'expenses'
  | 'payroll'
  | 'makeups'
  | 'practice-rooms'
  | 'consultations'
  | 'practice'
  | 'lessons'
  | 'resources'
  | 'teachers'
  | 'calendar'
  | 'recitals'
  | 'curriculum'
  | 'assignments'
  | 'achievements'
  | 'song-stamps'
  | 'reports'
  | 'bookings'
  | 'services'
  | 'members'
  | 'instructors'
  | 'passes'
  | 'retail'
  | 'sales'
  | 'inventory'
  | 'shuttle'
  | 'journals'
  | 'medications'
  | 'notices'
  | 'settings'
  | 'account';

export type StudentDetailTab =
  | 'info'
  | 'classes'
  | 'attendance'
  | 'tuition'
  | 'textbooks'
  | 'consultations'
  | 'practice'
  | 'videos'
  | 'memo';
