/** 상품 목록·폼 UI 문구 */
export const PRODUCT_LIST_COPY = {
  title: '상품',
  description: '상품명·가격·옵션을 관리합니다',
  add: '상품 등록',
  edit: '수정',
  searchPlaceholder: '상품명 검색',
  categoryAll: '전체 카테고리',
  categoryNone: '미분류',
  statusAll: '전체',
  statusActive: '판매중',
  statusInactive: '판매중지',
  emptyTitle: '등록된 상품이 없습니다',
  emptyDescription: '상품을 등록하면 목록에 표시됩니다',
  optionBadge: (count: number) => (count > 0 ? `옵션 ${count}개` : '단일 상품'),
  noOrg: '사업장을 선택해 주세요',
  loadError: '상품 목록을 불러오지 못했습니다',
  saveError: '상품 저장에 실패했습니다',
  createTitle: '상품 등록',
  editTitle: '상품 수정',
  nameLabel: '상품명',
  codeLabel: '상품코드',
  priceLabel: '판매가격',
  costLabel: '원가',
  categoryLabel: '카테고리',
  newCategoryLabel: '새 카테고리',
  newCategoryPlaceholder: '새 카테고리명 (선택)',
  activeLabel: '판매 여부',
  optionModeLabel: '옵션',
  optionNone: '옵션 없음',
  optionYes: '옵션 있음',
  optionNameLabel: '옵션명',
  optionSkuLabel: 'SKU',
  optionPriceLabel: '옵션 가격',
  optionCostLabel: '옵션 원가',
  optionActiveLabel: '판매',
  addOption: '옵션 추가',
  removeOption: '삭제',
  optionRequired: '옵션이 있는 경우 옵션명을 입력해 주세요',
  categoryManage: '카테고리',
  categoryManageTitle: '카테고리 관리',
  categoryManageHint: '상품에 연결할 카테고리를 추가·수정합니다. 다단계 분류는 지원하지 않습니다.',
  categoryNameLabel: '카테고리명',
  categoryNamePlaceholder: '예: 음료',
  categoryAdd: '추가',
  categoryRename: '이름 수정',
  categoryDeactivate: '비활성화',
  categoryActivate: '활성화',
  categoryActive: '사용중',
  categoryInactive: '비활성',
  categoryEmptyTitle: '카테고리가 없습니다',
  categoryEmptyDescription: '위에서 카테고리를 추가해 주세요',
  categoryAdded: '카테고리가 추가되었습니다.',
  categoryRenamed: '카테고리명이 수정되었습니다.',
  categoryDeactivated: '카테고리를 비활성화했습니다.',
  categoryActivated: '카테고리를 활성화했습니다.',
  categoryLoadError: '카테고리 목록을 불러오지 못했습니다',
  categorySaveError: '카테고리 저장에 실패했습니다',
  save: '저장',
  cancel: '취소',
  saving: '저장 중…',
} as const;
